#define 	HELIOS_MOUSE_BUTTON_1   0
 
#define 	HELIOS_MOUSE_BUTTON_2   1
 
#define 	HELIOS_MOUSE_BUTTON_3   2
 
#define 	HELIOS_MOUSE_BUTTON_4   3
 
#define 	HELIOS_MOUSE_BUTTON_5   4
 
#define 	HELIOS_MOUSE_BUTTON_6   5
 
#define 	HELIOS_MOUSE_BUTTON_7   6
 
#define 	HELIOS_MOUSE_BUTTON_8   7
 
#define 	HELIOS_MOUSE_BUTTON_LAST   HELIOS_MOUSE_BUTTON_8
 
#define 	HELIOS_MOUSE_BUTTON_LEFT   HELIOS_MOUSE_BUTTON_1
 
#define 	HELIOS_MOUSE_BUTTON_RIGHT   HELIOS_MOUSE_BUTTON_2
 
#define 	HELIOS_MOUSE_BUTTON_MIDDLE   HELIOS_MOUSE_BUTTON_3